version: '3.8'

services:
  pingapp_db:
    image: postgres:18-alpine
    container_name: pingapp-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pingapp-pgdata:/var/lib/postgresql
    networks:
      - pingapp-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.3-management-alpine
    container_name: pingapp-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - pingapp-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  pingapp-api:
    image: pingapp-api:latest
    build:
      context: .
      dockerfile: PingApp.Api/Dockerfile
    container_name: pingapp-api-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=pingapp_db;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - RabbitMq__Uri=rabbitmq://rabbitmq
      - RabbitMq__Username=${RABBITMQ_USER}
      - RabbitMq__Password=${RABBITMQ_PASSWORD}
      - ApiSettings__TelegramBotApiKey=${INTERNAL_API_KEY}
    networks:
      - pingapp-net
    depends_on:
      pingapp_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  backend-worker:
    image: pingapp-backend-worker:latest
    build:
      context: .
      dockerfile: PingApp.Worker/Dockerfile
    container_name: pingapp-worker-service
    restart: always
    environment:
      - ConnectionStrings__DefaultConnection=Host=pingapp_db;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - ElasticConfiguration__Uri=http://elasticsearch:9200
      - RabbitMq__Uri=rabbitmq://rabbitmq
      - RabbitMq__Username=${RABBITMQ_USER}
      - RabbitMq__Password=${RABBITMQ_PASSWORD}
    networks:
      - pingapp-net
    depends_on:
      pingapp_db:
        condition: service_healthy
      elasticsearch:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  telegram-bot:
    image: pingapp-telegram-bot:latest
    build:
      context: .
      dockerfile: telegram_bot/Dockerfile
    container_name: pingapp-telegram-bot-service
    restart: always
    environment:
      - BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - RABBITMQ_URI=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
      - CSHARP_API_URL=http://pingapp-api:8080/api
      - API_KEY=${INTERNAL_API_KEY}
    depends_on:
      rabbitmq:
        condition: service_healthy
      pingapp-api:
        condition: service_started
    networks:
      - pingapp-net

  pgadmin:
    image: dpage/pgadmin4:9.16
    container_name: pingapp-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - pingapp-net
    depends_on:
      - pingapp_db

  redis:
    image: redis:8.0-alpine
    container_name: pingapp-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - pingapp-redis-data:/data
    networks:
      - pingapp-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.2
    container_name: pingapp-elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - pingapp-elastic-data:/usr/share/elasticsearch/data
    networks:
      - pingapp-net

  kibana:
    image: docker.elastic.co/kibana/kibana:9.4.2
    container_name: pingapp-kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - pingapp-net

  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    container_name: pingapp-jaeger
    restart: always
    ports:
      - "16686:16686"
      - "4317:4317"
    networks:
      - pingapp-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.154.0
    container_name: pingapp-otel-collector
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./deploy/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"
    depends_on:
      - jaeger
    networks:
      - pingapp-net

  prometheus:
    image: prom/prometheus:v3.12.0
    container_name: pingapp-prometheus
    restart: always
    volumes:
      - ./deploy/prometheus.yml:/etc/prometheus/prometheus.yml
      - pingapp-prometheus-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector
    networks:
      - pingapp-net

  grafana:
    image: grafana/grafana:13.1.0
    container_name: pingapp-grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - pingapp-grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - pingapp-net

networks:
  pingapp-net:
    driver: bridge

volumes:
  pingapp-pgdata:
  pingapp-redis-data:
  pingapp-elastic-data:
  pingapp-prometheus-data:
  pingapp-grafana-data: